enfermedad(gripe).
enfermedad(malaria).
enfermedad(rubeola).
enfermedad(tuberculosis).
enfermedad(anemia).
enfermedad(hepatitis).
sintoma(tos).
sintoma(dolorpecho).
sintoma(mareos).
sintoma(fiebre).
sintoma(dolorcabeza).
sintoma(vomitos).
sintoma(escalofrios).
sintoma(dolormuscular).
sintoma(faringitis).
sintoma(inflamacionganglios).
sintoma(ojosrojos).
sintoma(faringitis).
sintoma(inflamacionganglios).
sintoma(ojosrojos).
sintoma(expectoracion).
sintoma(sudor).
sintoma(nauseas).
sintoma(desnutricion).
sintoma(colorpielamarillo).
sintoma(diarrea).
area_especialista(otorrino).
area_especialista(nutricionista).
area_especialista(endocrinologo).
area_especialista(clinico).
area_especialista(nutricionista).
area_especialista(clinico).
sintomade(tos,gripe).
sintomade(dolorpecho,gripe).
sintomade(mareos,gripe).
sintomade(fiebre,gripe).
sintomade(dolorcabeza,gripe).
sintomade(fiebre,malaria).
sintomade(vomitos,malaria).
sintomade(escalofrios,malaria).
sintomade(dolorcabeza,malaria).
sintomade(dolormuscular,malaria).
sintomade(fiebre,rubeola).
sintomade(faringitis,rubeola).
sintomade(inflamacionganglios,rubeola).
sintomade(ojosrojos,rubeola).
sintomade(tos,tuberculosis).
sintomade(expectoracion,tuberculosis).
sintomade(sudor,tuberculosis).
sintomade(desnutricion,anemia).
sintomade(nauseas,anemia).
sintomade(vomitos,anemia).
sintomade(colorpielamarillo,hepatitis).
sintomade(diarrea,hepatitis).
especialistade(otorrino,gripe).
especialistade(nutricionista,anemia).
especialistade(endocrinologo,hepatitis).
especialistade(clinico,rubeola).
especialistade(nutricionista,tuberculosis).
especialistade(clinico,malaria).
