//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BaseProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        public Especialidad()
        {
            this.MedicoPorEspecialidas = new HashSet<MedicoPorEspecialida>();
        }
    
        public int Id { get; set; }
        public string Especialidad1 { get; set; }
    
        public virtual ICollection<MedicoPorEspecialida> MedicoPorEspecialidas { get; set; }
    }
}
