//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BaseProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio
    {
        public Estudio()
        {
            this.EstudioPacientes = new HashSet<EstudioPaciente>();
        }
    
        public int Id { get; set; }
        public string Estudio1 { get; set; }
    
        public virtual ICollection<EstudioPaciente> EstudioPacientes { get; set; }
    }
}
