//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BaseProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicoPorEspecialidads
    {
        public int Id { get; set; }
        public int MatriculaMedico { get; set; }
        public int IdEspecialidad { get; set; }
        public Nullable<int> Especialidad_Id { get; set; }
        public string Medico_Id { get; set; }
    
        public virtual Especialidads Especialidads { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
