//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BaseProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Diagnosticoes = new HashSet<Diagnostico>();
            this.EstudioPacientes = new HashSet<EstudioPaciente>();
            this.Guardias = new HashSet<Guardia>();
            this.HistorialPacientes = new HashSet<HistorialPaciente>();
            this.Turnoes = new HashSet<Turno>();
            this.ObraSocials = new HashSet<ObraSocial>();
            this.Sintomas = new HashSet<Sintoma>();
        }
    
        public int IdPaciente { get; set; }
        public int DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string FechaNacimiento { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> Contacto { get; set; }
        public string Sexo { get; set; }
    
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        public virtual ICollection<EstudioPaciente> EstudioPacientes { get; set; }
        public virtual ICollection<Guardia> Guardias { get; set; }
        public virtual ICollection<HistorialPaciente> HistorialPacientes { get; set; }
        public virtual ICollection<Turno> Turnoes { get; set; }
        public virtual ICollection<ObraSocial> ObraSocials { get; set; }
        public virtual ICollection<Sintoma> Sintomas { get; set; }
    }
}
