//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BaseProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sintoma
    {
        public Sintoma()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int IdSintoma { get; set; }
        public string Sintoma1 { get; set; }
    
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
