//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.BaseProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnoes
    {
        public int Id { get; set; }
        public int DniPaciente { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> MatriculaMedico { get; set; }
        public Nullable<int> IdRecepcionista { get; set; }
        public string Medico_Id { get; set; }
        public Nullable<int> Paciente_DNI { get; set; }
        public Nullable<int> Recepcionista_Id { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Recepcionistas Recepcionistas { get; set; }
    }
}
