///////////////////////////////////////////////////////////
//  Clinico.cs
//  Implementation of the Class Clinico
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:15:21
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class Clinico : Medico {

		public Clinico(){

		}

		~Clinico(){

		}

		public void AgregarClinico(){

		}

	}//end Clinico

}//end namespace DOMAIN