///////////////////////////////////////////////////////////
//  Diagnostico.cs
//  Implementation of the Class Diagnostico
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:15:54
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class Diagnostico {

		private string diagnostico;
		private DateTime Fecha;
		private int Id;
		private int MM;
		private int Paciente;
		private bool RequiereEstudio;
		public DOMAIN.Medico m_Medico;

		public Diagnostico(){

		}

		~Diagnostico(){

		}

		public void AgregarDiagnostico(){

		}

	}//end Diagnostico

}//end namespace DOMAIN