///////////////////////////////////////////////////////////
//  EstudiosPaciente.cs
//  Implementation of the Class EstudiosPaciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:16:50
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class EstudiosPaciente {

		private string Comentarios;
		private int DNI;
		private int Estudio;
		private DateTime Fecha;
		private int MM;
		public DOMAIN.Paciente m_Paciente;

		public EstudiosPaciente(){

		}

		~EstudiosPaciente(){

		}

		public void SolicitarTurnoPaciente(){

		}

	}//end EstudiosPaciente

}//end namespace DOMAIN