///////////////////////////////////////////////////////////
//  Estudios.cs
//  Implementation of the Class Estudios
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:16:30
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DOMAIN {
	public class Estudios {

		private string Descripción;
		private int Id;

		public Estudios(){

		}

		~Estudios(){

		}

		public void AgregarEstudio(){

		}

	}//end Estudios

}//end namespace DOMAIN