///////////////////////////////////////////////////////////
//  Guardia.cs
//  Implementation of the Class Guardia
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:17:13
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class Guardia {

		private int DNIPaciente;
		private DateTime Fecha;
		private int Id;
		private int Matricula;
		public DOMAIN.Paciente m_Paciente;

		public Guardia(){

		}

		~Guardia(){

		}

		public void SolicitarGuardia(){

		}

	}//end Guardia

}//end namespace DOMAIN