///////////////////////////////////////////////////////////
//  Historial_Paciente.cs
//  Implementation of the Class Historial_Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:17:31
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DOMAIN {
	public class Historial_Paciente {

		private string Comentarios;
		private int DNIPaciente;
		private DateTime Fecha;
		private int Id;
		private int MatriculaMedico;

		public Historial_Paciente(){

		}

		~Historial_Paciente(){

		}

	}//end Historial_Paciente

}//end namespace DOMAIN