///////////////////////////////////////////////////////////
//  Horarios.cs
//  Implementation of the Class Horarios
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:17:58
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class Horarios {

		private int id;
		private string Turno;
		public DOMAIN.Horarios_Medicos m_Horarios_Medicos;

		public Horarios(){

		}

		~Horarios(){

		}

		public void AgregarHoario(){

		}

	}//end Horarios

}//end namespace DOMAIN