///////////////////////////////////////////////////////////
//  Obra Social.cs
//  Implementation of the Class Obra Social
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:25
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DOMAIN {
	public class ObraSocial {

		private int IdObraSocial;
		private string obraSocial;

		public ObraSocial(){

		}

		~ObraSocial(){

		}

	}//end Obra Social

}//end namespace DOMAIN