///////////////////////////////////////////////////////////
//  ObraSocial_Paciente.cs
//  Implementation of the Class ObraSocial_Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:41
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class ObraSocial_Paciente {

		private int DNI_Paciente;
		private string ObraSocial;
		public DOMAIN.Paciente m_Paciente;

		public ObraSocial_Paciente(){

		}

		~ObraSocial_Paciente(){

		}

		public void AgregarObraSocialPaciente(){

		}

	}//end ObraSocial_Paciente

}//end namespace DOMAIN