///////////////////////////////////////////////////////////
//  Paciente.cs
//  Implementation of the Class Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:57
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



//using Domain Model;
//using DOMAIN;
//using DAL;

namespace DOMAIN {
	public class Paciente {

		private string Apellido;
		private int Celular;
		private int d;
		private string Dirección;
		private int DNI;
		private DateTime FechaNacimiento;
		private int IdPaciente;
		private string Nombre;
		//public Domain Model.Medicos m_Medicos;
		public DOMAIN.Historial_Paciente m_Historial_Paciente;
		public DOMAIN.Turno m_Turno;
		public DOMAIN.Diagnostico m_Diagnostico;

		public Paciente(){

		}

		~Paciente(){

		}

	}//end Paciente

}//end namespace DOMAIN