///////////////////////////////////////////////////////////
//  Recepcionista.cs
//  Implementation of the Class Recepcionista
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:20:53
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class Recepcionista {

		private string Apellido;
		private int DNI;
		private int Id;
		private string Nombre;
		public DOMAIN.Turno m_Turno;

		public Recepcionista(){

		}

		~Recepcionista(){

		}

		public void AgregarRecepcionista(){

		}

	}//end Recepcionista

}//end namespace DOMAIN