///////////////////////////////////////////////////////////
//  Turno.cs
//  Implementation of the Class Turno
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:21:44
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DOMAIN {
	public class Turno {

		private int DNIPaciente;
		private DateTime Fecha;
		private int Id;
		private int IdRecepcionista;
		private int MarticulaM;

		public Turno(){

		}

		~Turno(){

		}

		public void SolicitarTurno(){

		}

	}//end Turno

}//end namespace DOMAIN