///////////////////////////////////////////////////////////
//  EstudiosPaciente.cs
//  Implementation of the Class EstudiosPaciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:16:50
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace Domain
{
	public class EstudioPaciente {

		[Key]
		public int Id { get; set; }
		public int IdMedico { get; set; }
        public int IdPaciente { get; set; }
        public int IdEstudio { get; set; }
        public string Comentarios { get; set; }		
		public DateTime Fecha { get; set; }
		

		public EstudioPaciente(){

		}

		public void SolicitarTurnoPaciente(){

		}

	}//end EstudiosPaciente

}//end namespace DOMAIN