///////////////////////////////////////////////////////////
//  Estudios.cs
//  Implementation of the Class Estudios
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:16:30
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace Domain
{
	public class Estudio {

		[Key]
		public int Id { get; set; }
        public string Nombre { get; set; }

        public Estudio(){

		}

		public void AgregarEstudio(){

		}

	}//end Estudios

}//end namespace DOMAIN