///////////////////////////////////////////////////////////
//  Estudios.cs
//  Implementation of the Class Estudios
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:16:30
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace DOMAIN {
	public class Estudio {

		public string Descripción { get; set; }
		public Guid Id { get; set; }

		public Estudio(){

		}

		public void AgregarEstudio(){

		}

	}//end Estudios

}//end namespace DOMAIN