///////////////////////////////////////////////////////////
//  Horarios.cs
//  Implementation of the Class Horarios
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:17:58
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Domain
{
	public class Horario {

		public Guid id { get; set; }
		public string horario { get; set; }
		//public DOMAIN.Horarios_Medicos m_Horarios_Medicos;

		public Horario(){

		}



		public void AgregarHoario(){

		}

	}//end Horarios

}//end namespace DOMAIN