///////////////////////////////////////////////////////////
//  Horarios_Medicos.cs
//  Implementation of the Class Horarios_Medicos
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:18:25
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class Horarios_Profesional {

		public Guid id { get; set; }
		public int idHorario { get; set; }
		public int Matricula { get; set; }
		//public Medico Especialista m_Medico Especialista;
		//public DOMAIN.Clinico m_Clinico;

		public Horarios_Profesional(){

		}


		public void AgregarHorarioProfesional(){

		}

	}//end Horarios_Medicos

}//end namespace DOMAIN