///////////////////////////////////////////////////////////
//  Medico Especialista.cs
//  Implementation of the Class Medico Especialista
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:01
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Domain
{
	public class MedicoEspecialista  {
		/// <summary>
		/// Agregar el contexto al dbset
		/// </summary>
		/// 
		public int Id { get; set; }
		public int IdEspecialidad { get; set; }
		public int IdMedico { get; set; }

	}//end Medico Especialista

}//end namespace DOMAIN