///////////////////////////////////////////////////////////
//  Medico Especialista.cs
//  Implementation of the Class Medico Especialista
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:01
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using DOMAIN;
namespace DOMAIN {
	public class MedicoEspecialista : Medico {

		public MedicoEspecialista(){

		}

		~MedicoEspecialista(){

		}

		public void AgregarEspecialista(){

		}

	}//end Medico Especialista

}//end namespace DOMAIN