///////////////////////////////////////////////////////////
//  Obra Social.cs
//  Implementation of the Class Obra Social
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:25
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace Domain
{
	public class ObraSocial {

		[Key]
		public int Id { get; set; }
		public string Nombre { get; set; }

		public ObraSocial(){

		}



	}//end Obra Social

}//end namespace DOMAIN