///////////////////////////////////////////////////////////
//  ObraSocial_Paciente.cs
//  Implementation of the Class ObraSocial_Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:41
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain
{
	public class ObraSocial_Paciente {

		public int DNI_Paciente { get; set; }
		public string ObraSocial { get; set; }
		public Domain.Paciente m_Paciente { get; set; }

		public ObraSocial_Paciente(){

		}



		public void AgregarObraSocialPaciente(){

		}

	}//end ObraSocial_Paciente

}//end namespace DOMAIN