///////////////////////////////////////////////////////////
//  ObraSocial_Paciente.cs
//  Implementation of the Class ObraSocial_Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:41
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace Domain
{
	public class ObraSocial_Paciente {

		[Key]
		public int Id { get; set; }
		public int IdPaciente { get; set; }
		public int IdObraSocial { get; set; }

		public ObraSocial_Paciente(){

		}



		

	}//end ObraSocial_Paciente

}//end namespace DOMAIN