///////////////////////////////////////////////////////////
//  Paciente.cs
//  Implementation of the Class Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:19:57
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;



//using Domain Model;
//using DOMAIN;
//using DAL;

namespace Domain
{
	public class Paciente {
		[Key]
        public int IdPaciente { get; set; }
        public int DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Contacto { get; set; }
		public string Dirección { get; set; }
		public string Sexo { get; set; }



		//public string ObraSocial { get;set; }
		//public Domain Model.Medicos m_Medicos;


		public Paciente(){

		}


	}//end Paciente

}//end namespace DOMAIN