///////////////////////////////////////////////////////////
//  Recepcionista.cs
//  Implementation of the Class Recepcionista
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:20:53
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Domain  {
	public class Recepcionista {

		public string Apellido { get; set; }
		public int DNI { get; set; }
		public Guid Id { get; set; }
		public string Nombre { get; set; }
		//public DOMAIN.Turno m_Turno;

		public Recepcionista(){

		}



		public void AgregarRecepcionista(){

		}

	}//end Recepcionista

}//end namespace DOMAIN