///////////////////////////////////////////////////////////
//  Sintomas_Paciente.cs
//  Implementation of the Class Sintomas_Paciente
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:21:28
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace Domain
{
	public class Sintomas_Paciente {

		public Guid Paciente { get; set; }
		public Guid Sintoma { get; set; }
		public Domain.Paciente m_Paciente;

		public Sintomas_Paciente(){

		}



		public void AgregarSintomasPaciente(){

		}

	}//end Sintomas_Paciente

}//end namespace DOMAIN