///////////////////////////////////////////////////////////
//  Sintomas.cs
//  Implementation of the Class Sintomas
//  Generated by Enterprise Architect
//  Created on:      17-ago.-2022 22:21:11
//  Original author: ailus
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace Domain
{
	public class Sintoma {

		[Key]
		public int IdSintoma { get; set; }
		public string sintoma { get; set; }

		public Sintoma(){

		}



		public void AgregarSintoma(){

		}

	}//end Sintomas

}//end namespace DOMAIN