///////////////////////////////////////////////////////////
//  DiagnosticarBLL.cs
//  Implementation of the Class DiagnosticarBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:46:46
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DOMAIN;

namespace BLL {
	public class DiagnosticarBLL {

		public DiagnosticarBLL(){

		}

		~DiagnosticarBLL(){

		}

		/// 
		/// <param name="diagnostico"></param>
		public void ActualizarDiagnostico(Diagnostico diagnostico){

		}

		public List<string> BuscarCoincidencias(){

			return null;
		}

		/// 
		/// <param name="diagnostico"></param>
		public Diagnostico CrearDiagnostico(Diagnostico diagnostico){

			return null;
		}

		public List<Diagnostico> ListDiagnostico(){

			return null;
		}

	}//end DiagnosticarBLL

}//end namespace BLL