///////////////////////////////////////////////////////////
//  EspecialidadBLL.cs
//  Implementation of the Class EspecialidadBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:47:22
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Domain;

namespace BLL {
	public class EspecialidadBLL {

        #region Singleton
        private readonly static EspecialidadBLL _instance = new EspecialidadBLL();

        public static EspecialidadBLL Current
        {
            get
            {
                return _instance;
            }
        }

        private EspecialidadBLL()
        {
            //Implement here the initialization code
        }
        #endregion


        /// 
        /// <param name="especialidad"></param>
        public void AgregarEspecialidad(Especialidad especialidad){

		}

		/// 
		/// <param name="int"></param>
		public void BajaEspecialidad(int id){

		}

		public List<Especialidad> ListarEspecialidad(){

			return null;
		}

		/// 
		/// <param name="especialidad"></param>
		public void ModificarExpecialidad(Especialidad especialidad){

		}

	}//end EspecialidadBLL

}//end namespace BLL