///////////////////////////////////////////////////////////
//  GuardiaBLL.cs
//  Implementation of the Class GuardiaBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:47:59
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DOMAIN;

namespace BLL {
	public class GuardiaBLL {

		public GuardiaBLL(){

		}

		~GuardiaBLL(){

		}

		/// 
		/// <param name="paciente"></param>
		public void AsignarGuardia(Paciente paciente){

		}

		/// 
		/// <param name="int"></param>
		public void BajaGuardia(int id){

		}

		/// 
		/// <param name="guardia"></param>
		public void ModificarGuardia(Guardia guardia){

		}

	}//end GuardiaBLL

}//end namespace BLL