///////////////////////////////////////////////////////////
//  MedicoBLL.cs
//  Implementation of the Class MedicoBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:48:15
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BLL;
using DOMAIN;

namespace BLL {
	public class MedicoBLL {

		public BLL.EspecialidadBLL m_EspecialidadBLL;
		public BLL.PacienteBLL m_PacienteBLL;

		public MedicoBLL(){

		}

		~MedicoBLL(){

		}

		/// 
		/// <param name="medico"></param>
		public void AltaMedico(Medico medico){

		}

		/// 
		/// <param name="int"></param>
		public void BajaMedico(int id){

		}

		/// 
		/// <param name="matricula"></param>
		public List<DateTime> GetDisponibilidad(int matricula){

			return null;
		}

		public List<Medico> ListarMedico<Medico>(){

			return null;
		}

		/// 
		/// <param name="medico"></param>
		public void ModificarMedico(Medico medico){

		}

		public Medico SeleccionarMedico(){

			return null;
		}

	}//end MedicoBLL

}//end namespace BLL