///////////////////////////////////////////////////////////
//  PacienteBLL.cs
//  Implementation of the Class PacienteBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:48:43
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BLL;
using DOMAIN;
using DataAccess.Repo.Sql;
using AutoMapper;
using System.Runtime.InteropServices;
using DataAccess.Tools;
using System.Data;
using DataAccess.Interfaces;
using DataAccess.BaseProd;
using System.Linq;
using Business.Interfaces;
using Business.DTOs;
using Business.Factory;
using ServiceLayer.Mapper;
using Paciente = DataAccess.BaseProd.Paciente;

namespace BLL {
	public class PacienteBLL:IGenericBusiness<PacienteDTO> {

        private SysEntitiesContext _context = new SysEntitiesContext();

        #region Singleton
        private readonly static PacienteBLL _instance = new PacienteBLL();

        public static PacienteBLL Current
        {
            get
            {
                return _instance;
            }
        }

        #endregion


        public PacienteBLL()
        {
            //Implement here the initialization code
        }

        public void Create(PacienteDTO obj)
        {
            var dtoToEntity = MapperHelper.GetMapper().Map<Paciente>(obj);
            BusinesFactory.GenericRepo().Insert(dtoToEntity);
        }

        public void Delete(PacienteDTO obj)
        {
            throw new NotImplementedException();
        }

        public void Update(PacienteDTO obj)
        {
            throw new NotImplementedException();
        }

        public List<PacienteDTO> GetAll()
        {
            throw new NotImplementedException();
        }
       
        public List<string> GetObraSocial()
        {
           var obs= _context.ObraSocials.Select(x => x.ObraSocial1);
            var list = new List<string>();

            foreach (var item in obs)
            {
                list.Add(item); 
            }
            return list;
        }




    }//end PacienteBLL

}//end namespace BLL