///////////////////////////////////////////////////////////
//  PacienteBLL.cs
//  Implementation of the Class PacienteBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:48:43
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BLL;
using DOMAIN;
using DataAccess.Repo.Sql;

namespace BLL {
	public class PacienteBLL {

        //public BLL.EstudioBLL m_EstudioBLL;
        //public BLL.TurnoBLL m_TurnoBLL;
        //public BLL.GuardiaBLL m_GuardiaBLL;


        #region Singleton
        private readonly static PacienteBLL _instance = new PacienteBLL();

		PacientesRepo repo= new PacientesRepo();

        public static PacienteBLL Current
        {
            get
            {
                return _instance;
            }
        }

        public PacienteBLL()
        {
            //Implement here the initialization code
        }
        #endregion



        /// <summary>
        /// 
        /// </summary>
        /// <param name="paciente"></param>
        public void AltaPaciente(Paciente paciente){
            try
            {

            }
            catch (Exception ex)
            {
				throw ex;
            }
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="ID"></param>
		public void BajaPaciente(int ID){

		}


		/// <summary>
		/// 
		/// </summary>
		/// <param name="ID"></param>
		/// <returns></returns>
		public Paciente  BuscarPaciente(int ID){

			return null;
		}

		/// <summary>
		/// 
		/// USAR AUTOMAPPER PARA CONVERTIR EL OBJ DE PACIENTEBLL EN EL OBJ DE LA BD
		/// </summary>
		/// <returns></returns>
		public IEnumerable<Paciente> ListarPaciente(){
			var paciente = repo.GetAll();
			return null;
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="paciente"></param>
		public void ModificarPaciente(Paciente paciente){

		}

	}//end PacienteBLL

}//end namespace BLL