///////////////////////////////////////////////////////////
//  SintomaBLL.cs
//  Implementation of the Class SintomaBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:48:58
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BLL;
using DOMAIN;

namespace BLL {
	public class SintomaBLL {

		public BLL.EnfermedadBLL m_EnfermedadBLL;
		public BLL.DiagnosticarBLL m_DiagnosticarBLL;
        #region Singleton
        private readonly static SintomaBLL _instance = new SintomaBLL();

        public static SintomaBLL Current
        {
            get
            {
                return _instance;
            }
        }

        private SintomaBLL()
        {
            //Implement here the initialization code
        }
        #endregion




        /// 
        /// <param name="sintoma"></param>
        public void AltaSintoma(Sintoma sintoma){

		}

		/// 
		/// <param name="int"></param>
		public void BajaSintoma(int ID){

		}

		public List<Sintoma> ListarSintoma(){

			return null;
		}

		/// 
		/// <param name="sintoma"></param>
		public void ModificarSintoma(Sintoma sintoma){

		}

	}//end SintomaBLL

}//end namespace BLL