///////////////////////////////////////////////////////////
//  EspecialidadBLL.cs
//  Implementation of the Class EspecialidadBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:47:22
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
//using Domain;
using BLL.Interfaces;
using BLL.Dto;
using BLL.MapperConfig;
using Services;
using DAL.Interfaces;
using DAL.Factory;
using DAL.Models;
using Services.BLL;
using System.Diagnostics.Tracing;
using System.Reflection.Metadata;
using Services.BLL.Exepciones;
//using DAL.Models;

namespace BLL.Business {
	public class EspecialidadBLL : IGenericBusiness<EspecialidadDto>
    {

        private readonly static EspecialidadBLL _instance = new EspecialidadBLL();


        public static EspecialidadBLL Current
        {
            get
            {
                return _instance;
            }
        }

        IGenericRepository<Especialidad> genericRepository = FactoryDAL._especialidadRepository;



        public void Insert(EspecialidadDto obj)
        {
            try
            {
                var dtoToentity = new Especialidad()
                {
                    Id = obj.Id,
                    Nombre = obj.Nombre,

                };
                genericRepository.Insert(dtoToentity);
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
           
        }

        public void Update(EspecialidadDto obj)
        {
            try
            {
                var dtoToentity = new Especialidad()
                {
                    Id = obj.Id,
                    Nombre = obj.Nombre,

                };
                genericRepository.Update(dtoToentity);
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
           
        }

        public IEnumerable<EspecialidadDto> GetAll()
        {
            try
            {
                List<DAL.Models.Especialidad> listado = genericRepository.GetAll().ToList();
                //   var entity = MapperHelper.GetMapper().
                //Map<List<Especialidad>, List<EspecialidadDto>>(genericRepository.GetAll().ToList());

                var entity = MapperHelper.GetMapper().
            Map<List<Especialidad>, List<EspecialidadDto>>(genericRepository.GetAll().ToList());
                return entity;
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
        
        }

        public EspecialidadDto GetOne(int? guid)
        {
            try
            {
                var op = MapperHelper.GetMapper().Map<EspecialidadDto>(genericRepository.GetOne(guid));

                return op;
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
            
        }

        public void Delete(int? guid)
        {
            try
            {
                var op = genericRepository.GetOne(guid);
                if (op != null)
                {
                    genericRepository.Delete(op);
                }
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
            
        }
    }//end EspecialidadBLL

}//end namespace BLL