///////////////////////////////////////////////////////////
//  SintomaBLL.cs
//  Implementation of the Class SintomaBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:48:58
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BLL;
//using Domain;
using BLL.Interfaces;
using BLL.MapperConfig;
using Services;
using DAL.Interfaces;
using DAL.Factory;
using DAL.Models;
using BLL.Dto;
using Services.BLL.Exepciones;
//using DAL.Models;

namespace BLL.Business {
	public class SintomaBLL : IGenericBusiness<SintomaDto>
    {
        private readonly static SintomaBLL _instance = new SintomaBLL();


        public static SintomaBLL Current
        {
            get
            {
                return _instance;
            }
        }

        IGenericRepository<Sintoma> genericRepository = FactoryDAL._sintomaRepository;



        public void Insert(SintomaDto obj)
        {
            try
            {
                var dtoToentity = new Sintoma()
                {
                    IdSintoma = obj.IdSintoma,
                    Nombre = obj.sintoma

                };
                genericRepository.Insert(dtoToentity);
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
            
        }

        public void Update(SintomaDto obj)
        {
            try
            {
                var dtoToentity = new Sintoma()
                {
                    IdSintoma = obj.IdSintoma,
                    Nombre = obj.sintoma

                };
                genericRepository.Update(dtoToentity);
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
            
        }

        public IEnumerable<SintomaDto> GetAll()
        {
            try
            {
                var entity = MapperHelper.GetMapper().
        Map<List<SintomaDto>>(genericRepository.GetAll());

                return entity;
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
           
        }

        public SintomaDto GetOne(int? guid)
        {
            try
            {
                var op = MapperHelper.GetMapper().Map<SintomaDto>(genericRepository.GetOne(guid));

                return op;
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
            
        }

        public void Delete(int? guid)
        {
            try
            {
                var op = genericRepository.GetOne(guid);
                if (op != null)
                {
                    genericRepository.Delete(op);
                }
            }
            catch (Exception ex)
            {
                ExceptionManager.Current.Handle(ex);

                throw;
            }
            
        }

       
    }//end SintomaBLL

}//end namespace BLL