///////////////////////////////////////////////////////////
//  TurnoBLL.cs
//  Implementation of the Class TurnoBLL
//  Generated by Enterprise Architect
//  Created on:      18-ago.-2022 20:49:16
//  Original author: Ailin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Domain;

namespace BLL.Business {
	public class TurnoBLL {

        #region Singleton
        private readonly static TurnoBLL _instance = new TurnoBLL();

        public static TurnoBLL Current
        {
            get
            {
                return _instance;
            }
        }

        public TurnoBLL()
        {

        }

        #endregion

        /// 
        /// <param name="Turno"></param>
        public void AltaTurno(Turno Turno){

		}

		/// 
		/// <param name="paciente"></param>
		public void AsignarTurno(Paciente paciente){

		}

		/// 
		/// <param name="int"></param>
		public void BajaTurno(int ID){

		}

		/// 
		/// <param name="turno"></param>
		public void ConfirmaTurno(Turno turno){

		}

		/// 
		/// <param name="turno"></param>
		public void ModificarTurno(Turno turno){

		}

		/// 
		/// <param name="int"></param>
		public List<Turno> TurnosPaciente(Paciente ID){

			return null;
		}

	}//end TurnoBLL

}//end namespace BLL